language: swift
osx_image: xcode9.3beta
branches:
  only:
    - master
env:
  global:
    - SDK="iphonesimulator"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7" MODE="test" CONFIGURATION="Debug" SCHEME="Resource"
    - DESTINATION="OS=11.0,name=iPhone 7" MODE="test" CONFIGURATION="Debug" SCHEME="Resource"
    - DESTINATION="OS=11.0,name=iPad Pro (10.5-inch)" MODE="test" CONFIGURATION="Debug" SCHEME="Resource"
    - DESTINATION="OS=11.0,name=iPhone 7" MODE="build" CONFIGURATION="Release" SCHEME="Resource"
    - DESTINATION="OS=11.0,name=iPad Pro (10.5-inch)" MODE="build" CONFIGURATION="Release" SCHEME="Resource"
script:
  - set -o pipefail
  - xcodebuild "$MODE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIGURATION" | xcpretty
